name: minify
run-name: Minify JS/CSS/HTML [gh-pages branch]

on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  checkout-minify-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the current repository
      - uses: actions/checkout@v3

      # Clone the other repository
      - name: Clone other repository
        run: |
          git clone https://github.com/autosam/Tamaweb.git tamaweb
          cd tamaweb
          git checkout develop

      # Copy files from the other repository to the current repository
      - name: Copy files
        run: |
          cp -r tamaweb/* .

      # Install NodeJS and CLI tools
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install -g terser
      - run: npm install -g csso-cli
      - run: npm install -g html-minifier

      # Perform minification, overwriting original files
      - run: for i in ./src/*.js; do terser $i --compress -o $i; done
      - run: csso ./styles.css -o ./styles.css
      - run: html-minifier --collapse-boolean-attributes --collapse-whitespace --minify-css --minify-js --minify-urls --remove-attribute-quotes --remove-comments --remove-empty-attributes --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-style-link-type-attributes --remove-tag-whitespace --use-short-doctype -o index.html index.html
      
      # Add untracked files
      - run: git add .

      # (Force) push changes to `gh-pages` branch
      - run: |
          git config user.name autosam
          git config user.email autosam.sm@gmail.com
          git commit -am 'Automated minify of ${{ github.sha }}'
          git push --force -u origin main:gh-pages
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
